title: My Clean Site
description: A simple Jekyll site with clear structure
baseurl: "/ikzoeknietmijnkat"   # your repo name as baseurl
permalink: pretty                # enable pretty URLs (folders with index.html)
theme: minima                   # your theme
